/// Flutter icons CustomIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();


  static const _kFontFam = 'CustomIcons';
  static const dynamic _kFontPkg = null;

  static const IconData washing_machine = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_point_to_right = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gear = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menu = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData slumber = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logout = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData kitchen = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tv = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData work_table = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData parking = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shower = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData carpet = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData air_conditioner = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cooler = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heater = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData food = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData book = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filter = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wifi = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fridge = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData renewable_energy = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mosque = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData disk = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart1 = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData air_conditioner1 = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phone = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData water_filter1 = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lcd = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData close = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData close1 = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData more = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logout1 = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
